# Generated by Django 4.0.3 on 2022-05-13 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_category_alter_article_options_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
